### ISSUE TITLE
Unable to performan offline or online validation

### ISSUE THREAD

**Issue by nfacha** [GorokhovDV/safetynetattestation#1]
Its always triggering this exception: 

```
"name": "Exception",
    "message": "Local certificate bundle is unavailable",
    "code": 0,
    "type": "SafetyNet\\Statement\\Exception\\RootCertificateError",
    "file": "/var/www/html/project-name/vendor/gorokhovdv/safetynet-verification/src/RootGoogleCertService.php",
    "line": 41,
    ```

Is there something missing?

**Comment by GorokhovDV** [comment]
It means  that you have not valid SSL root cert in system for Google. I fixed it by catching this exception, It should download last valid CA and save them in local TMP folder.

**Comment by GorokhovDV** [comment]
Update lib for 0.0.3 version please (https://github.com/GorokhovDV/safetynetattestation/releases/tag/0.0.3)
